import requests
import json

# API URL
endpoint = "http://localhost:8080/daftar-calon-klien"

headers = {"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzWTczVmh0d2RvWG1ZdVRWRktlV0FMYXROWFkzajdoaGMzaHNqR24tRmJZIn0.eyJleHAiOjE2NzI4Mzk4MjUsImlhdCI6MTY3MjgwMzgyNiwiYXV0aF90aW1lIjoxNjcyODAzODI1LCJqdGkiOiI5ZmIyM2VlOC00N2JhLTQ5YjYtYjA2ZC1lYmFhNzFlM2UyYTAiLCJpc3MiOiJodHRwOi8vdGlnZXIudG9yY2hlLmlkOjgwMTAvYXV0aC9yZWFsbXMvZXhhbXBsZSIsInN1YiI6ImY6MjVkYWMzYTEtOTljNy00MTBlLTlmNDktNTVmOTE2ZmIzOTI2OmJhcGFzX2JhbmR1bmciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmcm9udGVuZC1zZHAiLCJub25jZSI6ImVhZWYzNGM4LTljYjMtNDllMS04OTIxLTVlODkzMjA5NDBkZSIsInNlc3Npb25fc3RhdGUiOiJkOTE1ZjA1Zi1lZDMzLTQ5OWUtYjIyNi0zNGUxYjg4OTBjYzgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzI0MDAiLCIqIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZnJvbnRlbmQtc2RwIjp7InJvbGVzIjpbImFjY2Vzc192aWV3Il19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6ImQ5MTVmMDVmLWVkMzMtNDk5ZS1iMjI2LTM0ZTFiODg5MGNjOCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidXB0X3R5cGVfbmFtZSI6IkJhbGFpIFBlbWFzeWFyYWthdGFuIiwidXB0X2lkIjoiNzA3IiwibGV2ZWxfaWQiOiIyMTIiLCJwZXJtaXNzaW9uIjpbImFjY2Vzc192aWV3Il0sInByZWZlcnJlZF91c2VybmFtZSI6ImJhcGFzX2JhbmR1bmciLCJ0eXBlIjoidXB0Iiwia2Fud2lsX25hbWUiOiJKYXdhIEJhcmF0IiwidXB0X25hbWUiOiJCQVBBUyBCQU5EVU5HIiwibGV2ZWxfbmFtZSI6IlVBVCIsInVzZXJfaWQiOiIxNjEiLCJ1cHRfdHlwZV9pZCI6IkpVMTAiLCJrYW53aWxfaWQiOiIxMiIsImFjdGl2ZV9sZXZlbCI6IjIxMiIsImVtYWlsIjoiMTIzMTIzQGdtYWlsLmNvbSJ9.gsnn_OJM91s1LrNwxf4hFMs6_b-ZQvXSSAQVr3x4kcLgccSZzDHhdbEPZMpeqNAgUPM5y8eta7h8p-WDSjUBUwbZP5U25pdn6FhYESVcnUX9aNdNA99I2iU2pCkvRx2ZrI35z1uJ3Z6y3rVsgsjidO0F5QPbVrOQOvSrigfaQogdMGR2vPi6TXxlVC5LiwrmX2woWSqA7mF-XSGrcqaFGJ_enzrwwhZ2-noemfk3xMLnu4EEL6B-iYwaz2U6UsDXiVOqwQ57ZubC6ci_W2VSg1tXwbMMTkuYmJSeEa7vLlpaSj0plYbLRz2-hLnqvF9DIxOxvjTYPjIxiEyPbkpCFg"}

# read input json file
file = open('collections/CreateCalonKlien.json', 'r')
data = file.read()
request_json = json.loads(data)

# print(request_json)

# make POST request with json input body
response = requests.post(endpoint, headers=headers, data=request_json)
print(response.content)


# print(requests.post(endpoint, data=data, headers=headers).json())